### ISSUE TITLE
Break out Engine from Scene code

### ISSUE THREAD

**Issue by TatumCreative** [glamjs/glam#2]
Engine should be separate, and allow for things like loops, asset loading, manifests?, maybe even canvas resizing.

```js
var engine = Engine()
var renderer = engine.renderer
var scene = engine.scene

engine.on('init', function() {
  scene.add( ... )
})

engine.on('update', function() {
  doSomething()
})
```

**Comment by jwerle** [comment]
+1

**Comment by TatumCreative** [comment]
This is implemented on the dev branch, although the renderer is still handling the canvas adding and resizing.

https://github.com/glamjs/glam/commits/dev
https://github.com/glamjs/glam/blob/dev/docs/api/engine.md
