### ISSUE TITLE
mesh parameter

### ISSUE THREAD

**Issue by mattdesl** [glamjs/glam#4]
I am a fan of the way ThreeJS orders the mesh parameters:

```js
new THREE.Mesh(goemetry[, material])
```

Any particular reason Glam goes against this?

**Comment by TatumCreative** [comment]
Because I never, never remembered the order :) Easy enough to change it back.

**Comment by TatumCreative** [comment]
07d40e4675ad1a173cfa820cf81ac6ae0e081f7a fixes this, on dev only at the moment.
